# Generated by Django 2.1 on 2018-09-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=512)),
            ],
            options={
                'swappable': swapper.swappable_setting('input', 'CollectedInput'),
            },
        ),
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('help', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CollectionInstrumentType',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('max_instrument_inputs_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('max_instrument_inputs', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('is_singleton', models.BooleanField(default=False)),
                ('restrict', models.BooleanField()),
                ('multiple', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='collection_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionRequest'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionGroup'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.Measure'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='response_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.ResponsePolicy'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='suggested_responses',
            field=models.ManyToManyField(to='input.SuggestedResponse'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='input.CollectionInstrumentType'),
        ),
        migrations.AddField(
            model_name='collectedinput',
            name='collection_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectedinput_set', to='input.CollectionRequest'),
        ),
        migrations.AddField(
            model_name='collectedinput',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectedinput_set', to='input.CollectionInstrument'),
        ),
        migrations.AddField(
            model_name='collectedinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
