# Generated by Django 2.1 on 2018-09-13 21:19

from django.db import migrations, models
import django.db.models.deletion
import swapper
import input.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=512)),
            ],
            options={
                'swappable': swapper.swappable_setting('input', 'CollectedInput'),
            },
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('help', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_instrument_inputs_per_user', models.PositiveIntegerField(default=1)),
                ('max_instrument_inputs', models.PositiveIntegerField(null=True)),
            ],
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResponsePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('is_singleton', models.BooleanField(default=False)),
                ('restrict', models.BooleanField()),
                ('multiple', models.BooleanField()),
            ],
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SuggestedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=512)),
            ],
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='collection_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='input.CollectionRequest'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionGroup'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.Measure'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='response_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.ResponsePolicy'),
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='suggested_responses',
            field=models.ManyToManyField(to='input.SuggestedResponse'),
        ),
        migrations.AddField(
            model_name='collectedinput',
            name='collection_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionRequest'),
        ),
        migrations.AddField(
            model_name='collectedinput',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionInstrument'),
        ),
    ]
