# Generated by Django 2.1 on 2018-09-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('any', 'Any input allowed'), ('none', 'No input allowed'), ('all-suggested', 'All suggested'), ('one-suggested', 'At least one suggested'), ('all-custom', 'All custom'), ('one-custom', 'At least one custom'), ('match', 'Input matches this data'), ('mismatch', "Input doesn't match this data"), ('contains', 'Input contains this data'), ('not-contains', 'Input does not contain this data')], default=None, max_length=20, null=True)),
                ('data', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionGroup',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('requirement_type', models.CharField(choices=[('all-pass', 'All cases must pass'), ('one-pass', 'At least one case must pass'), ('all-fail', 'All cases must fail')], default=True, max_length=20)),
                ('cases', models.ManyToManyField(to='input.Case')),
                ('child_groups', models.ManyToManyField(blank=True, related_name='parent_groups', to='input.ConditionGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_group',
            field=models.ForeignKey(limit_choices_to={'parent_groups': None}, on_delete=django.db.models.deletion.CASCADE, to='input.ConditionGroup'),
        ),
        migrations.AddField(
            model_name='condition',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='input.CollectionInstrument'),
        ),
        migrations.AddField(
            model_name='condition',
            name='parent_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_conditions', to='input.CollectionInstrument'),
        ),
    ]
