# Generated by Django 2.1 on 2018-09-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='data',
            new_name='match_data',
        ),
    ]
