sudo: false
language: python
cache: pip
git:
  depth: 1
  quite: true
  
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
install:
  - pip install -qqq Django~=$DJANGO.0
  - pip install -qqq -r requirements.txt
  - pip install -qqq -r requirements-tests.txt
script:
  - python testproj/manage.py test --settings=testproj.settings.test

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO=2.0
  - python: "2.7"
    env: DJANGO=2.1
