sudo: false
language: python
cache: pip
git:
  depth: 1
  quite: true
  
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
install:
  - pip install -qqq requirements-test.txt
  - pip install -qqq requirements.txt
script:
  - cd testproj && ./manage.py test --settings=testproj.settings.test

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO=2.0.9
  - python: "2.7"
    env: DJANGO=2.1.2
  - python: "3.4"
    env: DJANGO=2.1.2
