sudo: false
language: python
cache: pip
git:
  depth: 1

python:
  - "3.8"
  - "3.9"
  - "3.10-dev"
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
  - DJANGO=3.2
install:
  - pip install -qqq Django~=$DJANGO.0
  - pip install -qqq djangorestframework
  - pip install -qqq -r requirements.txt
  - pip install -qqq -r requirements-tests.txt
script:
  - python testproj/manage.py test --settings=testproj.settings.test

matrix:
  exclude:
  - python: "3.10-dev"
    env: DJANGO=2.1

