# Generated by Django 2.1 on 2018-11-14 20:36

from django.db import migrations, models
import django_input_collection.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_input_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='data_getter',
            field=models.CharField(default='', max_length=512, validators=[django_input_collection.models.validators.DataSourceValidator]),
            preserve_default=False,
        ),
    ]
