# Generated by Django 2.1.4 on 2019-01-22 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    dependencies = [
        ('django_input_collection', '0005_auto_20181116_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundSuggestedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('collection_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_suggested_responses', to='django_input_collection.CollectionInstrument')),
                ('suggested_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_input_collection.SuggestedResponse')),
            ],
            options={
                'swappable': swapper.swappable_setting('django_input_collection', 'BoundSuggestedResponse'),
            },
        ),
        migrations.AddField(
            model_name='collectioninstrument',
            name='suggested_responses_new',
            field=models.ManyToManyField(blank=True, related_name='collectioninstrument_new', through=settings.INPUT_BOUNDSUGGESTEDRESPONSE_MODEL, to='django_input_collection.SuggestedResponse'),
        ),
    ]
