# Generated by Django 2.1.7 on 2019-03-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_input_collection', '0008_auto_20190206_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectioninstrument',
            old_name='group',
            new_name='segment',
        ),
    ]
