# Generated by Django 2.1.7 on 2019-03-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_input_collection', '0009_auto_20190304_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninstrument',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_instruments', to='django_input_collection.CollectionGroup'),
        ),
        migrations.AlterField(
            model_name='collectioninstrument',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_instruments', to='django_input_collection.CollectionGroup'),
        ),
    ]
