# Generated by Django 2.1.4 on 2019-03-08 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_input_collection", "0010_auto_20190306_2040"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectioninstrument",
            options={"ordering": ("segment_id", "order", "pk")},
        ),
    ]
