# Generated by Django 6.1.1 on 2026-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_input_collection", "0013_alter_collectedinput_collector_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectioninstrument",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
