# Generated by Django 2.1.4 on 2019-01-22 21:13

from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    dependencies = [
        ('django_input_collection', '0005_auto_20181116_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundSuggestedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'swappable': swapper.swappable_setting('django_input_collection', 'BoundSuggestedResponse'),
            },
        ),
        migrations.AlterField(
            model_name='collectioninstrument',
            name='suggested_responses',
            field=models.ManyToManyField(blank=True, through='django_input_collection.BoundSuggestedResponse', to='django_input_collection.SuggestedResponse'),
        ),
        migrations.AddField(
            model_name='boundsuggestedresponse',
            name='collection_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_suggested_responses', to='django_input_collection.CollectionInstrument'),
        ),
        migrations.AddField(
            model_name='boundsuggestedresponse',
            name='suggested_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_input_collection.SuggestedResponse'),
        ),
    ]
