# Generated by Django 2.1.4 on 2019-01-22 21:03

from django.conf import settings
from django.db import migrations


def copy_implicit_m2m_data_to_boundsuggestedresponse(apps, schema_editor):
    # Extract
    CollectionInstrument = apps.get_model('django_input_collection', 'CollectionInstrument')
    legacy_field_values = CollectionInstrument.suggested_responses.through.objects.values()

    # Re-insert
    swapped_app, swapped_model = settings.INPUT_BOUNDSUGGESTEDRESPONSE_MODEL.split('.', 1)
    BoundSuggestedResponse = apps.get_model(swapped_app, swapped_model)
    BoundSuggestedResponse.objects.bulk_create([
        BoundSuggestedResponse(**fields) for fields in legacy_field_values
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('django_input_collection', '0006_auto_20190122_2117'),
    ]

    operations = [
        migrations.RunPython(copy_implicit_m2m_data_to_boundsuggestedresponse),
    ]
