# Generated by Django 2.1 on 2018-09-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedInput_MySQL_JSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectedinput_set', to='input.CollectionRequest')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectedinput_set', to='input.CollectionInstrument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliticalRally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RallyPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('collection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionRequest')),
                ('rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PoliticalRally')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('collection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionRequest')),
            ],
        ),
        migrations.AddField(
            model_name='politicalrally',
            name='collection_requests',
            field=models.ManyToManyField(through='core.RallyPoll', to='input.CollectionRequest'),
        ),
    ]
