# Generated by Django 2.1 on 2018-09-14 20:53

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import input.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedInput_MySQL_JSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionRequest')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.CollectionInstrument')),
            ],
            options={
                'abstract': False,
            },
            bases=(input.models.utils.DatesMixin, models.Model),
        ),
    ]
